spring:
  profiles:
    active: 
      - dev
---
spring:
  profiles: dev
    application:
      name: mcloud-config-lfm-dev
---
spring:
     profiles: test
     application: 
       name: mcloud-config-lfm-test